-- V10: 매거진(칵테일 가이드/스토리) 통합 콘텐츠 도메인
-- 목적: 파편화된 글 콘텐츠(news / cocktail_news / guide_detail)를 대체할 단일 정본 모델.
-- 설계 원칙 (3원칙):
--   ① 태그는 기존 tag 테이블 재사용 → magazine_article_tag 조인만 신설.
--      동네/도시는 tag.type 에 'CITY'/'NEIGHBORHOOD' 값만 추가(스키마 변경 없음).
--   ② 칵테일 스펙은 복사하지 않는다 → content 블록의 cocktail_id 로 cocktail 마스터를 참조.
--   ③ 본문은 블록 배열을 JSONB 로 저장 → 새 블록 타입 추가 시 마이그레이션 불필요.
-- 컬럼 snake_case. 응답 JSON snake_case(spring.jackson SNAKE_CASE).

-- ═══════════════════════════════════════════════════════════════════════
-- 1) 매거진 글
-- ═══════════════════════════════════════════════════════════════════════
CREATE TABLE magazine_article (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             VARCHAR(120)  NOT NULL,
    title            VARCHAR(255)  NOT NULL,
    title_lines      JSONB,                       -- ["줄1","줄2"] 커버 줄바꿈 의도. NULL 이면 자동 줄바꿈
    dek              VARCHAR(500),                -- 부제/요약 한 줄
    category         VARCHAR(20)   NOT NULL,      -- STORY | MOOD | BASE | SEASON
    subcategory      VARCHAR(100),                -- 자유 문자열(칩): 클래식 · 진 · 여름 ...
    cover_image      VARCHAR(1000),               -- 4:3 커버용
    hero_image       VARCHAR(1000),               -- 16:9 상세 상단용
    thumbnail        VARCHAR(1000),               -- 3:2 목록 카드용
    image_caption    VARCHAR(500),
    author_name      VARCHAR(100),
    author_bio       VARCHAR(500),                -- 저장만(현재 화면 미노출)
    author_avatar    VARCHAR(1000),               -- 저장만
    content          JSONB         NOT NULL DEFAULT '[]'::jsonb,  -- 블록 배열
    refs             JSONB         NOT NULL DEFAULT '{}'::jsonb,  -- {related_article_slugs, sources, cocktail_ids}
    reading_time_min INTEGER,                     -- word_count 로 서버가 계산
    word_count       INTEGER,                     -- 저장만(계산 원본)
    view_count       INTEGER       NOT NULL DEFAULT 0,
    is_featured      BOOLEAN       NOT NULL DEFAULT false,        -- 커버 스토리 자동화용
    status           VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',      -- DRAFT | PUBLISHED
    published_at     TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_magazine_article_slug UNIQUE (slug)
);

-- 목록 피드(발행분, 최신순) / 카테고리 탭 피드
CREATE INDEX idx_magazine_feed     ON magazine_article (status, published_at DESC);
CREATE INDEX idx_magazine_category ON magazine_article (category, status, published_at DESC);

-- ═══════════════════════════════════════════════════════════════════════
-- 2) 글 ↔ 태그 (기존 tag 테이블 재사용, 조인만 신설)
--    tag.type 에 'CITY' / 'NEIGHBORHOOD' / 'MOOD' / 'BASE' / 'SEASON' / 'OCCASION' 사용.
-- ═══════════════════════════════════════════════════════════════════════
CREATE TABLE magazine_article_tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    CONSTRAINT fk_mat_article FOREIGN KEY (article_id) REFERENCES magazine_article (id) ON DELETE CASCADE,
    CONSTRAINT fk_mat_tag     FOREIGN KEY (tag_id)     REFERENCES tag (id)              ON DELETE CASCADE,
    CONSTRAINT uk_mat UNIQUE (article_id, tag_id)
);
CREATE INDEX idx_mat_tag ON magazine_article_tag (tag_id);

-- ═══════════════════════════════════════════════════════════════════════
-- 3) 기존 뉴스 콘텐츠 백필 (선택 · 안전 가드)
--    실제 정본 테이블이 news 인지 cocktail_news 인지 환경마다 다를 수 있어 존재 여부로 분기.
--    plain TEXT 본문은 단일 paragraph 블록으로 감싸 content(JSONB)에 이관.
--    ⚠️ 운영 반영 전 정본 테이블/카테고리 매핑을 팀과 한 번 확인할 것.
-- ═══════════════════════════════════════════════════════════════════════
DO $$
BEGIN
  IF to_regclass('public.news') IS NOT NULL THEN
    INSERT INTO magazine_article
      (slug, title, dek, category, thumbnail, hero_image, cover_image,
       author_name, content, view_count, is_featured, status, published_at, created_at)
    SELECT
      'news-' || n.id,
      n.title,
      n.summary,
      'STORY',                                   -- 기존 news.category(BEGINNER/TREND/...)는 subcategory 로 옮기고 상위는 STORY 로 통일
      n.image_url, n.image_url, n.image_url,
      'onz 에디터',
      jsonb_build_array(jsonb_build_object('type','paragraph','text', COALESCE(n.content, ''))),
      COALESCE(n.view_count, 0),
      COALESCE(n.featured, false),
      'PUBLISHED',
      COALESCE(n.published_at, n.created_at, CURRENT_TIMESTAMP),
      COALESCE(n.created_at, CURRENT_TIMESTAMP)
    FROM news n
    ON CONFLICT (slug) DO NOTHING;

    -- 기존 news.category 를 subcategory 로 보존
    UPDATE magazine_article a
       SET subcategory = n.category
      FROM news n
     WHERE a.slug = 'news-' || n.id AND a.subcategory IS NULL;
  END IF;
END $$;
