-- V12: 기존 가이드(guide/guide_detail)를 매거진(magazine_article)에 GUIDE 카테고리로 흡수.
--   - magazine.id = 기존 guide.part 를 보존(앱 가이드 탭의 Part 뱃지·정렬·딥링크 유지). id 는 GENERATED BY DEFAULT 라 명시 삽입 가능.
--   - guide_detail 각 행을 heading(subtitle) + image(image_url) + paragraph(description) 블록으로 변환해 content(JSONB) 구성.
--   - subtitle/description 의 마크다운 강조(*) 는 제거(기존 앱이 stripMarkdownEmphasis 로 제거하던 것과 동치).
-- 재실행 안전: slug 충돌 시 무시.

INSERT INTO magazine_article
  (id, slug, title, category, subcategory, cover_image, hero_image, thumbnail,
   author_name, content, refs, view_count, is_featured, status, published_at, created_at, updated_at)
SELECT
  g.part,
  'guide-' || g.part,
  g.title,
  'GUIDE',
  g.category,
  g.image_url, g.image_url, g.image_url,
  'onz 에디터',
  COALESCE((
    SELECT jsonb_agg(blk ORDER BY gd.display_order, sub)
    FROM guide_detail gd
    CROSS JOIN LATERAL (
      SELECT 1 AS sub,
             jsonb_build_object('type','heading','level',2,
               'text', regexp_replace(gd.subtitle, '\*', '', 'g')) AS blk
        WHERE gd.subtitle IS NOT NULL AND gd.subtitle <> ''
      UNION ALL
      SELECT 2, jsonb_build_object('type','image','src', gd.image_url)
        WHERE gd.image_url IS NOT NULL AND gd.image_url <> ''
      UNION ALL
      SELECT 3, jsonb_build_object('type','paragraph',
               'text', regexp_replace(gd.description, '\*', '', 'g'))
        WHERE gd.description IS NOT NULL AND gd.description <> ''
    ) blocks(sub, blk)
    WHERE gd.guide_part = g.part
  ), '[]'::jsonb),
  '{}'::jsonb,
  0, false, 'PUBLISHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM guide g
ON CONFLICT (slug) DO NOTHING;

-- 명시적 id 삽입으로 뒤처진 identity 시퀀스를 최대값으로 전진(향후 자동 id 충돌 방지).
SELECT setval(pg_get_serial_sequence('magazine_article','id'),
              GREATEST((SELECT MAX(id) FROM magazine_article), 1));
