-- Flyway baseline (V1): local 55432 DB pg_dump --schema-only snapshot.
-- Freezes the existing schema as-is. NOT a migration that mutates prod DB.
-- psql meta-commands stripped (not runnable via JDBC).

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cocktail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail (
    id bigint NOT NULL,
    abv_band character varying(255),
    base character varying(255),
    cocktailen character varying(255),
    cocktailkr character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    eng_name character varying(255) NOT NULL,
    glass_image_url character varying(255),
    glass_type character varying(255),
    hard_count integer DEFAULT 0 NOT NULL,
    image_url character varying(1000),
    ingredients_text character varying(255),
    kor_name character varying(255) NOT NULL,
    max_alcohol integer,
    min_alcohol integer,
    origin_text text,
    recommend_count integer DEFAULT 0 NOT NULL,
    season character varying(255),
    style character varying(255),
    taste_level character varying(255),
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: cocktail_bookmark; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail_bookmark (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    cocktail_id bigint NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: cocktail_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cocktail_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cocktail_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cocktail_flavor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail_flavor (
    id bigint NOT NULL,
    flavor_name character varying(50) NOT NULL,
    cocktail_id bigint NOT NULL
);


--
-- Name: cocktail_flavor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cocktail_flavor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cocktail_flavor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cocktail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cocktail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cocktail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cocktail_mood; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail_mood (
    id bigint NOT NULL,
    mood_name character varying(50) NOT NULL,
    cocktail_id bigint NOT NULL
);


--
-- Name: cocktail_mood_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cocktail_mood ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cocktail_mood_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cocktail_reaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail_reaction (
    id bigint NOT NULL,
    reaction_type character varying(255) NOT NULL,
    cocktail_id bigint NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT cocktail_reaction_reaction_type_check CHECK (((reaction_type)::text = ANY (ARRAY[('RECOMMEND'::character varying)::text, ('HARD'::character varying)::text])))
);


--
-- Name: cocktail_reaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cocktail_reaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cocktail_reaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cocktail_season; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail_season (
    cocktail_id bigint NOT NULL,
    seasons character varying(255),
    CONSTRAINT cocktail_season_seasons_check CHECK (((seasons)::text = ANY (ARRAY[('SPRING'::character varying)::text, ('SUMMER'::character varying)::text, ('FALL'::character varying)::text, ('WINTER'::character varying)::text])))
);


--
-- Name: cocktail_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cocktail_tag (
    id bigint NOT NULL,
    cocktail_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: cocktail_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cocktail_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cocktail_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guide; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guide (
    part integer NOT NULL,
    image_url character varying(1000),
    title character varying(255) NOT NULL
);


--
-- Name: guide_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guide_detail (
    id bigint NOT NULL,
    description text NOT NULL,
    display_order integer NOT NULL,
    image_url character varying(1000),
    subtitle character varying(255),
    guide_part integer NOT NULL
);


--
-- Name: guide_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guide_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guide_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingredient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredient (
    id bigint NOT NULL,
    amount character varying(255),
    name character varying(255),
    cocktail_id bigint NOT NULL
);


--
-- Name: ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    ad_term boolean,
    addr character varying(255),
    age integer,
    age_range smallint,
    age_term boolean NOT NULL,
    credential_id character varying(255) NOT NULL,
    email character varying(255),
    gender smallint,
    marketing_term boolean,
    name character varying(255),
    nickname character varying(255),
    phone character varying(255),
    profile character varying(255),
    role smallint NOT NULL,
    service_term boolean NOT NULL,
    social_login character varying(255),
    CONSTRAINT member_age_range_check CHECK (((age_range >= 0) AND (age_range <= 5))),
    CONSTRAINT member_gender_check CHECK (((gender >= 0) AND (gender <= 2))),
    CONSTRAINT member_role_check CHECK (((role >= 0) AND (role <= 2)))
);


--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: monitoring; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monitoring (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    age_range smallint,
    count bigint NOT NULL,
    device_number character varying(255) NOT NULL,
    gender smallint,
    onboarding_completed boolean DEFAULT false NOT NULL,
    member_id bigint,
    CONSTRAINT monitoring_age_range_check CHECK (((age_range >= 0) AND (age_range <= 5))),
    CONSTRAINT monitoring_gender_check CHECK (((gender >= 0) AND (gender <= 2)))
);


--
-- Name: monitoring_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.monitoring ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monitoring_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    query_text character varying(255) NOT NULL,
    user_id bigint
);


--
-- Name: search_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.search_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tag (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT tag_type_check CHECK (((type)::text = ANY (ARRAY[('FLAVOR'::character varying)::text, ('MOOD'::character varying)::text, ('BASE'::character varying)::text, ('GLASS'::character varying)::text])))
);


--
-- Name: tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cocktail_bookmark cocktail_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_bookmark
    ADD CONSTRAINT cocktail_bookmark_pkey PRIMARY KEY (id);


--
-- Name: cocktail_flavor cocktail_flavor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_flavor
    ADD CONSTRAINT cocktail_flavor_pkey PRIMARY KEY (id);


--
-- Name: cocktail_mood cocktail_mood_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_mood
    ADD CONSTRAINT cocktail_mood_pkey PRIMARY KEY (id);


--
-- Name: cocktail cocktail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail
    ADD CONSTRAINT cocktail_pkey PRIMARY KEY (id);


--
-- Name: cocktail_reaction cocktail_reaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_reaction
    ADD CONSTRAINT cocktail_reaction_pkey PRIMARY KEY (id);


--
-- Name: cocktail_tag cocktail_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_tag
    ADD CONSTRAINT cocktail_tag_pkey PRIMARY KEY (id);


--
-- Name: guide_detail guide_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guide_detail
    ADD CONSTRAINT guide_detail_pkey PRIMARY KEY (id);


--
-- Name: guide guide_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guide
    ADD CONSTRAINT guide_pkey PRIMARY KEY (part);


--
-- Name: ingredient ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT ingredient_pkey PRIMARY KEY (id);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- Name: monitoring monitoring_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitoring
    ADD CONSTRAINT monitoring_pkey PRIMARY KEY (id);


--
-- Name: search_history search_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_pkey PRIMARY KEY (id);


--
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- Name: tag uk1wdpsed5kna2y38hnbgrnhi5b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT uk1wdpsed5kna2y38hnbgrnhi5b UNIQUE (name);


--
-- Name: guide_detail uk6cy3iwsy32deggp5jtyt3pj7q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guide_detail
    ADD CONSTRAINT uk6cy3iwsy32deggp5jtyt3pj7q UNIQUE (guide_part, display_order);


--
-- Name: member uk8v5emh66mmwncroecijeesfg8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT uk8v5emh66mmwncroecijeesfg8 UNIQUE (credential_id);


--
-- Name: cocktail_bookmark uk_member_cocktail_bookmark; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_bookmark
    ADD CONSTRAINT uk_member_cocktail_bookmark UNIQUE (member_id, cocktail_id);


--
-- Name: cocktail_reaction uk_member_cocktail_reaction; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_reaction
    ADD CONSTRAINT uk_member_cocktail_reaction UNIQUE (member_id, cocktail_id);


--
-- Name: monitoring ukk6uc2ev5hm4ethnjj8b22v4xt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitoring
    ADD CONSTRAINT ukk6uc2ev5hm4ethnjj8b22v4xt UNIQUE (device_number);


--
-- Name: cocktail_reaction fk27pw5peax83kdup48f5twscp8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_reaction
    ADD CONSTRAINT fk27pw5peax83kdup48f5twscp8 FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- Name: cocktail_flavor fka4srvtm74hg57k881feri9wag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_flavor
    ADD CONSTRAINT fka4srvtm74hg57k881feri9wag FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- Name: monitoring fkaju041bys3tk0uqcbgub28pb1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitoring
    ADD CONSTRAINT fkaju041bys3tk0uqcbgub28pb1 FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: cocktail_reaction fkbvwp7mead81qc988bqxgbh7k8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_reaction
    ADD CONSTRAINT fkbvwp7mead81qc988bqxgbh7k8 FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: cocktail_mood fkgin82d80bkce002vbb7dseuus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_mood
    ADD CONSTRAINT fkgin82d80bkce002vbb7dseuus FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- Name: cocktail_tag fkl92n93e8pv59vugru0mtngais; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_tag
    ADD CONSTRAINT fkl92n93e8pv59vugru0mtngais FOREIGN KEY (tag_id) REFERENCES public.tag(id);


--
-- Name: cocktail_tag fkqq8r5oqwk8rbt8ao1yssop9pp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_tag
    ADD CONSTRAINT fkqq8r5oqwk8rbt8ao1yssop9pp FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- Name: cocktail_bookmark fkr25mqqqnwpysno9x5eboq99pq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_bookmark
    ADD CONSTRAINT fkr25mqqqnwpysno9x5eboq99pq FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: ingredient fkr545i032qtmrbso8d2bctkl7c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT fkr545i032qtmrbso8d2bctkl7c FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- Name: guide_detail fksee1nh66fflp5eh6wkje1yg51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guide_detail
    ADD CONSTRAINT fksee1nh66fflp5eh6wkje1yg51 FOREIGN KEY (guide_part) REFERENCES public.guide(part);


--
-- Name: cocktail_bookmark fksftafu5fyp0fdnkgy8q0v2yeo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_bookmark
    ADD CONSTRAINT fksftafu5fyp0fdnkgy8q0v2yeo FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- Name: cocktail_season fksx5folmui0tdgcyk2ieyhour4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cocktail_season
    ADD CONSTRAINT fksx5folmui0tdgcyk2ieyhour4 FOREIGN KEY (cocktail_id) REFERENCES public.cocktail(id);


--
-- PostgreSQL database dump complete
--


