-- ═══════════════════════════════════════════════════════════════════════
-- V2__admin.sql  —  관리자 기반 (T-17)
--   · admin_user       : 세션 폼로그인 대상 (BCrypt). 인메모리 하드코딩 대체 (F-03)
--   · admin_audit_log  : 모든 쓰기 작업 감사 로그 (before/after)
--   · inquiry          : 대시보드가 조회하나 테이블이 없어 500 (F-05) → 여기서 해소
-- 시드 관리자는 여기서 만들지 않는다. ADMIN_USERNAME/ADMIN_PASSWORD env 부트스트랩이 담당.
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS admin_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,           -- BCrypt
    role          VARCHAR(30)  NOT NULL DEFAULT 'ADMIN',   -- ADMIN | SUPER
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT,                            -- admin_user.id (nullable: 부트스트랩/시스템)
    action      VARCHAR(20)  NOT NULL,             -- CREATE | UPDATE | DELETE | REORDER | STATUS
    entity_type VARCHAR(40)  NOT NULL,             -- cocktail | cocktail_step | guide | news | inquiry ...
    entity_id   VARCHAR(60),
    before_json TEXT,                              -- 변경 전 스냅샷 (JSON 문자열, nullable)
    after_json  TEXT,                              -- 변경 후 스냅샷 (JSON 문자열, nullable)
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON admin_audit_log(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_admin  ON admin_audit_log(admin_id, created_at DESC);

CREATE TABLE IF NOT EXISTS inquiry (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT,
    email      VARCHAR(120),
    title      VARCHAR(200) NOT NULL,
    content    TEXT         NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'NEW',   -- NEW | READ | REPLIED
    reply      TEXT,
    replied_at TIMESTAMP,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_inquiry_status ON inquiry(status, created_at DESC);

-- 대시보드 문의 위젯이 비지 않도록 최소 시드 (운영 데이터 아님, 로컬/신규 DB 가시성용)
INSERT INTO inquiry (email, title, content, status) VALUES
    ('user1@example.com', '로그인이 안돼요',        '카카오 로그인 후 튕깁니다',        'NEW'),
    ('user2@example.com', '북마크가 사라졌어요',    '앱 재설치 후 보관함이 비었습니다', 'READ'),
    ('user3@example.com', '레시피 오탈자 제보',     '진토닉 재료 오타',                'REPLIED');
