-- V3: 레시피 제조 단계 (T-07)
-- cocktail_step / cocktail_tool / cocktail_tool_map / cocktail_made
-- 기존 cocktail(id) 를 FK 로 참조. ddl-auto:validate 와 정합하도록 엔티티와 컬럼/타입 일치.
-- 컬럼은 snake_case, 응답 JSON 은 camelCase(엔티티 필드명).

-- ── 제조 단계 ──────────────────────────────────────────────────────────
CREATE TABLE cocktail_step (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cocktail_id  BIGINT   NOT NULL REFERENCES cocktail(id) ON DELETE CASCADE,
    step_order   INTEGER  NOT NULL,
    instruction  TEXT     NOT NULL,
    tip          TEXT,
    image_url    VARCHAR(1000),
    duration_sec INTEGER,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cocktail_step UNIQUE (cocktail_id, step_order)
);
CREATE INDEX idx_cocktail_step ON cocktail_step(cocktail_id, step_order);

-- ── 도구 ───────────────────────────────────────────────────────────────
CREATE TABLE cocktail_tool (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE,
    icon_url VARCHAR(500)
);
CREATE TABLE cocktail_tool_map (
    cocktail_id BIGINT NOT NULL REFERENCES cocktail(id) ON DELETE CASCADE,
    tool_id     BIGINT NOT NULL REFERENCES cocktail_tool(id) ON DELETE CASCADE,
    PRIMARY KEY (cocktail_id, tool_id)
);

-- ── "만들어봤어요" 기록 (개인화 신호) ────────────────────────────────────
CREATE TABLE cocktail_made (
    member_id   BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    cocktail_id BIGINT NOT NULL REFERENCES cocktail(id) ON DELETE CASCADE,
    made_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (member_id, cocktail_id)
);

-- ═══════════════════════════════════════════════════════════════════════
-- 시드: 도구
-- ═══════════════════════════════════════════════════════════════════════
INSERT INTO cocktail_tool (name, icon_url) VALUES
    ('셰이커', NULL),
    ('바 스푼', NULL),
    ('지거', NULL),
    ('스트레이너', NULL),
    ('머들러', NULL),
    ('하이볼 글라스', NULL),
    ('마티니 글라스', NULL),
    ('쿠페 글라스', NULL);

-- ═══════════════════════════════════════════════════════════════════════
-- 시드: 실제 제조 단계 (kor_name 으로 매핑 — id 비의존)
-- 12개 클래식 칵테일
-- ═══════════════════════════════════════════════════════════════════════

-- 다이키리
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, tip, duration_sec)
SELECT id, 1, '셰이커에 얼음을 가득 채운다.', NULL, NULL::integer FROM cocktail WHERE kor_name='다이키리'
UNION ALL SELECT id, 2, '화이트 럼 60ml, 라임 주스 25ml, 심플 시럽 15ml를 넣는다.', '갓 짠 라임을 쓰면 향이 확 산다.', NULL::integer FROM cocktail WHERE kor_name='다이키리'
UNION ALL SELECT id, 3, '15초간 강하게 셰이킹한다.', NULL, 15 FROM cocktail WHERE kor_name='다이키리'
UNION ALL SELECT id, 4, '차갑게 식힌 쿠페 글라스에 더블 스트레이닝하여 따른다.', NULL, NULL::integer FROM cocktail WHERE kor_name='다이키리';

-- 모히또
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, tip, duration_sec)
SELECT id, 1, '글라스에 라임 4조각과 민트 잎 8~10장, 설탕 2티스푼을 넣는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='모히또'
UNION ALL SELECT id, 2, '머들러로 민트와 라임을 가볍게 으깬다.', '민트를 너무 세게 찧으면 쓴맛이 난다.', NULL::integer FROM cocktail WHERE kor_name='모히또'
UNION ALL SELECT id, 3, '으깬 얼음을 절반 채우고 화이트 럼 50ml를 붓는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='모히또'
UNION ALL SELECT id, 4, '탄산수로 채우고 바 스푼으로 가볍게 젓는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='모히또'
UNION ALL SELECT id, 5, '민트 가지로 가니시한다.', NULL, NULL::integer FROM cocktail WHERE kor_name='모히또';

-- 마가리타
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, tip, duration_sec)
SELECT id, 1, '글라스 테두리를 라임으로 적시고 소금을 묻힌다.', '소금은 테두리 절반만 묻히면 조절이 쉽다.', NULL::integer FROM cocktail WHERE kor_name='마가리타'
UNION ALL SELECT id, 2, '셰이커에 얼음, 데킬라 50ml, 쿠앵트로 20ml, 라임 주스 20ml를 넣는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='마가리타'
UNION ALL SELECT id, 3, '15초간 셰이킹한다.', NULL, 15 FROM cocktail WHERE kor_name='마가리타'
UNION ALL SELECT id, 4, '얼음을 넣은 글라스에 스트레이닝하여 따른다.', NULL, NULL::integer FROM cocktail WHERE kor_name='마가리타';

-- 위스키 사워
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, tip, duration_sec)
SELECT id, 1, '셰이커에 버번 위스키 50ml, 레몬 주스 25ml, 심플 시럽 15ml, 계란 흰자 1개를 넣는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='위스키 사워'
UNION ALL SELECT id, 2, '얼음 없이 먼저 드라이 셰이킹한다.', '흰자 거품을 살리는 핵심 단계.', 10 FROM cocktail WHERE kor_name='위스키 사워'
UNION ALL SELECT id, 3, '얼음을 넣고 다시 15초 셰이킹한다.', NULL, 15 FROM cocktail WHERE kor_name='위스키 사워'
UNION ALL SELECT id, 4, '락 글라스에 스트레이닝하고 앙고스투라 비터스를 몇 방울 떨어뜨린다.', NULL, NULL::integer FROM cocktail WHERE kor_name='위스키 사워';

-- 모스코 뮬
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '구리 머그에 얼음을 채운다.', NULL::integer FROM cocktail WHERE kor_name='모스코 뮬'
UNION ALL SELECT id, 2, '보드카 45ml와 라임 주스 15ml를 붓는다.', NULL::integer FROM cocktail WHERE kor_name='모스코 뮬'
UNION ALL SELECT id, 3, '진저비어로 채운다.', NULL::integer FROM cocktail WHERE kor_name='모스코 뮬'
UNION ALL SELECT id, 4, '라임 웨지로 가니시한다.', NULL::integer FROM cocktail WHERE kor_name='모스코 뮬';

-- 코스모폴리탄
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '셰이커에 얼음, 시트론 보드카 40ml, 쿠앵트로 15ml, 크랜베리 주스 30ml, 라임 주스 10ml를 넣는다.', NULL::integer FROM cocktail WHERE kor_name='코스모폴리탄'
UNION ALL SELECT id, 2, '15초간 셰이킹한다.', 15 FROM cocktail WHERE kor_name='코스모폴리탄'
UNION ALL SELECT id, 3, '차갑게 식힌 마티니 글라스에 스트레이닝한다.', NULL::integer FROM cocktail WHERE kor_name='코스모폴리탄'
UNION ALL SELECT id, 4, '오렌지 필로 향을 낸다.', NULL::integer FROM cocktail WHERE kor_name='코스모폴리탄';

-- 아메리카노
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '얼음을 채운 글라스에 캄파리 30ml와 스위트 베르무트 30ml를 붓는다.', NULL::integer FROM cocktail WHERE kor_name='아메리카노'
UNION ALL SELECT id, 2, '탄산수로 채운다.', NULL::integer FROM cocktail WHERE kor_name='아메리카노'
UNION ALL SELECT id, 3, '오렌지 슬라이스로 가니시한다.', NULL::integer FROM cocktail WHERE kor_name='아메리카노';

-- 진 피즈
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '셰이커에 진 45ml, 레몬 주스 25ml, 심플 시럽 15ml를 넣는다.', NULL::integer FROM cocktail WHERE kor_name='진 피즈'
UNION ALL SELECT id, 2, '얼음을 넣고 15초 셰이킹한다.', 15 FROM cocktail WHERE kor_name='진 피즈'
UNION ALL SELECT id, 3, '얼음을 넣은 하이볼 글라스에 스트레이닝한다.', NULL::integer FROM cocktail WHERE kor_name='진 피즈'
UNION ALL SELECT id, 4, '탄산수로 채운다.', NULL::integer FROM cocktail WHERE kor_name='진 피즈';

-- 블랙 러시안
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '락 글라스에 얼음을 채운다.', NULL::integer FROM cocktail WHERE kor_name='블랙 러시안'
UNION ALL SELECT id, 2, '보드카 50ml와 커피 리큐어 20ml를 붓는다.', NULL::integer FROM cocktail WHERE kor_name='블랙 러시안'
UNION ALL SELECT id, 3, '바 스푼으로 가볍게 젓는다.', NULL::integer FROM cocktail WHERE kor_name='블랙 러시안';

-- 카이피리냐
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, tip, duration_sec)
SELECT id, 1, '글라스에 라임 반 개를 조각내 넣고 설탕 2티스푼을 더한다.', NULL, NULL::integer FROM cocktail WHERE kor_name='카이피리냐'
UNION ALL SELECT id, 2, '머들러로 라임즙과 설탕을 으깬다.', '껍질 안쪽 흰 부분은 쓴맛이니 살살.', NULL::integer FROM cocktail WHERE kor_name='카이피리냐'
UNION ALL SELECT id, 3, '으깬 얼음을 채우고 카샤사 60ml를 붓는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='카이피리냐'
UNION ALL SELECT id, 4, '바 스푼으로 잘 젓는다.', NULL, NULL::integer FROM cocktail WHERE kor_name='카이피리냐';

-- 아페롤 스프리츠
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '와인 글라스에 얼음을 가득 채운다.', NULL::integer FROM cocktail WHERE kor_name='아페롤 스프리츠'
UNION ALL SELECT id, 2, '프로세코 90ml, 아페롤 60ml, 탄산수 30ml 순서로 붓는다.', NULL::integer FROM cocktail WHERE kor_name='아페롤 스프리츠'
UNION ALL SELECT id, 3, '오렌지 슬라이스로 가니시한다.', NULL::integer FROM cocktail WHERE kor_name='아페롤 스프리츠';

-- 프렌치 75
INSERT INTO cocktail_step (cocktail_id, step_order, instruction, duration_sec)
SELECT id, 1, '셰이커에 진 30ml, 레몬 주스 15ml, 심플 시럽 10ml와 얼음을 넣는다.', NULL::integer FROM cocktail WHERE kor_name='프렌치 75'
UNION ALL SELECT id, 2, '15초 셰이킹한다.', 15 FROM cocktail WHERE kor_name='프렌치 75'
UNION ALL SELECT id, 3, '샴페인 플루트에 스트레이닝한다.', NULL::integer FROM cocktail WHERE kor_name='프렌치 75'
UNION ALL SELECT id, 4, '차가운 샴페인으로 채우고 레몬 트위스트를 올린다.', NULL::integer FROM cocktail WHERE kor_name='프렌치 75';

-- ═══════════════════════════════════════════════════════════════════════
-- 시드: cocktail_tool_map (대표 도구 매핑 — 셰이킹 계열 칵테일)
-- ═══════════════════════════════════════════════════════════════════════
INSERT INTO cocktail_tool_map (cocktail_id, tool_id)
SELECT c.id, t.id FROM cocktail c, cocktail_tool t
WHERE c.kor_name IN ('다이키리','마가리타','위스키 사워','코스모폴리탄','진 피즈','프렌치 75')
  AND t.name IN ('셰이커','지거','스트레이너');

INSERT INTO cocktail_tool_map (cocktail_id, tool_id)
SELECT c.id, t.id FROM cocktail c, cocktail_tool t
WHERE c.kor_name IN ('모히또','카이피리냐')
  AND t.name IN ('머들러','바 스푼');
