-- V4: 뉴스 도메인 (T-08)
-- 신규 테이블 news (Prisma cocktail_news 와 무관 — 로컬 baseline 엔 그 테이블이 없음).
-- 컬럼 snake_case, 응답 JSON camelCase(엔티티 필드명).
-- source_url NULL 허용. featured 컬럼은 GET /news/featured 지원용(태스크 컬럼 목록의 확장).

CREATE TABLE news (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    summary      VARCHAR(500),
    content      TEXT,
    image_url    VARCHAR(1000),
    source       VARCHAR(100),
    source_url   VARCHAR(1000),
    category     VARCHAR(20)  NOT NULL DEFAULT 'TREND',
    featured     BOOLEAN      NOT NULL DEFAULT false,
    view_count   INTEGER      NOT NULL DEFAULT 0,
    published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_news_feed ON news(category, published_at DESC);

-- ═══════════════════════════════════════════════════════════════════════
-- 시드: 칵테일/위스키 관련 뉴스 12건 (그럴듯한 한국어. source_url 은 NULL)
-- category: BEGINNER 초심자 · EXPERT 전문가 · TREND 트렌드 · WHISKY 위스키 · CARTOON 만화
-- ═══════════════════════════════════════════════════════════════════════
INSERT INTO news (title, summary, content, source, category, featured, view_count, published_at) VALUES
('집에서 시작하는 첫 칵테일, 진토닉부터',
 '도구 없이도 만들 수 있는 입문용 3종을 정리했다.',
 '칵테일을 처음 시작한다면 값비싼 도구부터 살 필요는 없다. 진토닉, 스크루드라이버, 하이볼은 셰이커 없이 글라스 하나로 완성된다. 핵심은 좋은 얼음과 신선한 감귤류. 이 글에서는 각 레시피의 비율과 흔한 실수를 짚는다.',
 'ONZ 에디터', 'BEGINNER', true, 342, now() - interval '1 day'),

('바 스푼 하나로 달라지는 스터 기법',
 '젓는 칵테일의 온도와 희석을 다루는 법.',
 '마티니와 네그로니처럼 맑게 젓는 칵테일은 셰이킹과 목적이 다르다. 스터는 과한 희석 없이 차갑게 만드는 기술이다. 바 스푼을 글라스 벽에 붙여 부드럽게 30회 돌리는 것이 기본이다.',
 'ONZ 에디터', 'BEGINNER', false, 118, now() - interval '2 day'),

('2026년 봄 칵테일 트렌드: 저도수와 클래리파이드',
 '알코올을 낮추고 투명도를 높이는 흐름.',
 '올해 바 씬의 키워드는 저도수(low-ABV)와 밀크 클래리피케이션이다. 아페롤 스프리츠 같은 스프리츠 계열이 계속 강세이며, 우유로 산을 분리해 투명하게 만든 클래리파이드 칵테일이 파인다이닝 바에서 확산되고 있다.',
 'ONZ 트렌드랩', 'TREND', true, 501, now() - interval '3 day'),

('네그로니 위크, 올해도 돌아온다',
 '전 세계 바가 참여하는 네그로니 캠페인.',
 '진, 캄파리, 스위트 베르무트를 1:1:1로 섞는 네그로니는 이제 하나의 문화가 됐다. 네그로니 위크 기간 동안 참여 바들은 변형 레시피를 선보이고 수익 일부를 기부한다. 스발리아토, 보트 네그로니 등 파생 레시피도 함께 소개한다.',
 'ONZ 컬처', 'TREND', false, 233, now() - interval '4 day'),

('싱글 몰트 입문: 지역별 위스키 캐릭터',
 '스페이사이드부터 아일라까지 한눈에.',
 '스카치 싱글 몰트는 생산 지역에 따라 성격이 크게 갈린다. 스페이사이드는 과일과 꿀, 아일라는 강한 피트와 바다향이 특징이다. 입문자는 발베니나 글렌피딕 같은 균형 잡힌 스페이사이드부터 시작하는 것을 추천한다.',
 'ONZ 위스키데스크', 'WHISKY', true, 447, now() - interval '5 day'),

('하이볼의 과학: 탄산을 오래 살리는 법',
 '온도, 얼음, 붓는 순서가 전부다.',
 '완벽한 하이볼의 비밀은 위스키가 아니라 탄산 유지에 있다. 글라스와 위스키를 미리 차갑게 하고, 큰 얼음을 쓰며, 탄산수를 마지막에 얼음을 타고 흘려넣듯 부으면 기포 손실이 줄어든다. 젓기는 단 한 번이면 충분하다.',
 'ONZ 위스키데스크', 'WHISKY', false, 289, now() - interval '6 day'),

('바텐더가 말하는 흔한 홈바 실수 5가지',
 '전문가 시선으로 본 초보 함정.',
 '계량을 눈대중으로 하기, 오래된 감귤류 쓰기, 얼음을 아끼기, 글라스를 데우지 않기, 가니시를 생략하기. 현직 바텐더들이 공통으로 지적하는 다섯 가지 실수를 사례와 함께 풀었다.',
 'ONZ 인터뷰', 'EXPERT', false, 176, now() - interval '7 day'),

('오르자와 팔레르넘, 티키 시럽의 세계',
 '집에서 만드는 열대 칵테일 베이스.',
 '마이타이와 조합의 깊이는 시럽에서 나온다. 아몬드 베이스의 오르자, 향신료가 들어간 팔레르넘은 시판 제품도 있지만 직접 만들면 신선함이 다르다. 보관법과 기본 배합비를 정리했다.',
 'ONZ 에디터', 'EXPERT', false, 92, now() - interval '8 day'),

('만화로 보는 칵테일: 마티니 한 잔의 역사',
 '진과 베르무트가 만난 순간을 그림으로.',
 '드라이 마티니는 어떻게 "칵테일의 왕"이 됐을까. 19세기 말 등장설부터 007이 남긴 "젓지 말고 흔들어서"까지, 마티니를 둘러싼 이야기를 네 컷 만화 형식으로 풀었다.',
 'ONZ 카툰', 'CARTOON', false, 388, now() - interval '9 day'),

('만화로 보는 칵테일: 모히또와 헤밍웨이',
 '쿠바의 더위가 만든 청량한 한 잔.',
 '헤밍웨이가 사랑한 두 칵테일, 모히또와 다이키리. 아바나의 두 바를 오가며 마셨다는 일화를 만화로 옮겼다. 민트를 다루는 팁도 컷 사이에 숨어 있다.',
 'ONZ 카툰', 'CARTOON', false, 205, now() - interval '10 day'),

('제로 프루프 칵테일, 무알코올의 진화',
 '술 없이도 완성되는 복합적인 맛.',
 '무알코올 스피릿과 발효 음료가 정교해지면서 논알코올 칵테일의 수준이 급상승했다. 시드르 식초, 콤부차, 스파이스 시럽을 활용하면 알코올 없이도 층이 있는 맛을 낼 수 있다.',
 'ONZ 트렌드랩', 'TREND', false, 154, now() - interval '12 day'),

('얼음이 칵테일을 결정한다: 클리어 아이스 만들기',
 '집 냉동실에서 투명한 얼음 얻는 법.',
 '탁한 얼음은 빨리 녹고 맛을 흐린다. 방향성 냉동(directional freezing)을 쓰면 아이스박스와 냉동실만으로 바에서 쓰는 투명한 큐브를 만들 수 있다. 원리와 단계별 방법을 설명한다.',
 'ONZ 에디터', 'BEGINNER', false, 267, now() - interval '14 day');
