-- V5: 바 도메인 (T-10) + 게이트된 메뉴판 (T-12)
--
-- 백지 설계가 아니다. Cocktail_Node_backend/prisma/schema.prisma 의
--   model bar / bar_menu_category / bar_menu_item / bar_visit
-- 를 컬럼명·타입 그대로 이주한 것이다. 프론트(Cocktail_Front/src/Screens/Bar/**)가
-- 이미 그 계약(slug, nameKo, heroImage, isVisited, distanceKm)에 묶여 있다.
--
-- 컬럼은 snake_case, 응답 JSON 은 camelCase(엔티티 필드명). ddl-auto:validate 와
-- 정합하도록 엔티티 필드/타입을 아래 DDL 과 1:1로 맞춘다.
--
-- Node 대비 의도적 추가(2개, 둘 다 additive):
--   bar_menu_item.price_amount  : price 는 사장님 자유입력 String("시가") 이라 정렬·priceBand 산출 불가
--   bar_menu_item.cocktail_id   : 레시피북 연결 + BarDetail.signatureCocktails 산출원
-- PostGIS 미도입. lat/lng 복합 인덱스 + bounding-box 선필터 + Haversine 정렬(애플리케이션).

-- ── 바 ────────────────────────────────────────────────────────────────
CREATE TABLE bar (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(50)   NOT NULL UNIQUE,
    name_ko         VARCHAR(100)  NOT NULL,
    name_en         VARCHAR(100),
    address         VARCHAR(255)  NOT NULL,
    lat             NUMERIC(10,7) NOT NULL,
    lng             NUMERIC(10,7) NOT NULL,
    phone           VARCHAR(40),
    description     TEXT,
    hero_image      VARCHAR(500),
    hours           JSONB,
    status          VARCHAR(20)      NOT NULL DEFAULT 'ACTIVE',
    featured_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT now()
);
CREATE INDEX bar_status_idx  ON bar(status);
CREATE INDEX bar_lat_lng_idx ON bar(lat, lng);

-- ── 메뉴 카테고리 (자기참조 parent) ────────────────────────────────────
CREATE TABLE bar_menu_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id          BIGINT           NOT NULL REFERENCES bar(id) ON DELETE CASCADE,
    parent_id       BIGINT           REFERENCES bar_menu_category(id) ON DELETE CASCADE,
    name_ko         VARCHAR(100)     NOT NULL,
    name_en         VARCHAR(100),
    priority        DOUBLE PRECISION NOT NULL DEFAULT 0,
    category_image  VARCHAR(500),
    hide_side_image BOOLEAN          NOT NULL DEFAULT false,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT now()
);
CREATE INDEX bar_menu_category_bar_priority_idx ON bar_menu_category(bar_id, priority);

-- ── 메뉴 아이템 ────────────────────────────────────────────────────────
CREATE TABLE bar_menu_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id       BIGINT           NOT NULL REFERENCES bar(id) ON DELETE CASCADE,
    category_id  BIGINT           REFERENCES bar_menu_category(id) ON DELETE SET NULL,
    name         VARCHAR(255)     NOT NULL,
    name_en      VARCHAR(255),
    price        VARCHAR(255)     NOT NULL,   -- Node 계약: 자유입력 문자열("18,000", "시가")
    price_amount INTEGER,                     -- [추가] 정렬·priceBand 산출용. NULL 허용("시가")
    description  TEXT,
    notes        TEXT,
    menu_image   VARCHAR(500),
    priority     DOUBLE PRECISION NOT NULL DEFAULT 0,
    is_available BOOLEAN          NOT NULL DEFAULT true,
    cocktail_id  BIGINT           REFERENCES cocktail(id) ON DELETE SET NULL,  -- [추가]
    created_at   TIMESTAMP(6)     NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP(6)     NOT NULL DEFAULT now()
);
CREATE INDEX bar_menu_item_bar_cat_priority_idx ON bar_menu_item(bar_id, category_id, priority);
CREATE INDEX bar_menu_item_cocktail_idx ON bar_menu_item(cocktail_id);

-- ── 방문 체크 (토글) ───────────────────────────────────────────────────
CREATE TABLE bar_visit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT       NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    bar_id     BIGINT       NOT NULL REFERENCES bar(id) ON DELETE CASCADE,
    checked_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    CONSTRAINT uk_bar_visit_member_bar UNIQUE (member_id, bar_id)
);
CREATE INDEX bar_visit_member_checked_idx ON bar_visit(member_id, checked_at);

-- ══════════════════════════════════════════════════════════════════════
-- 시드: 서울 칵테일바 12곳
--   좌표는 실제 행정동 중심부 근사값. 상호/설명은 데모용 가상 데이터.
--   hero_image 는 EC2 nginx 가 서빙하는 /uploads/* 경로 규약을 따른다.
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO bar (slug, name_ko, name_en, address, lat, lng, phone, description, hero_image, hours, status, featured_weight) VALUES
('alice-cheongdam',   '앨리스 청담',   'Alice Cheongdam',  '서울 강남구 도산대로55길 15',    37.5245900, 127.0475800, '02-511-1001', '이상한 나라를 테마로 한 청담동의 스피크이지 바.',       '/uploads/bars/alice-cheongdam.webp',   '{"mon":"19:00-02:00","tue":"19:00-02:00","wed":"19:00-02:00","thu":"19:00-02:00","fri":"19:00-03:00","sat":"19:00-03:00","sun":"closed"}'::jsonb, 'ACTIVE', 9.5),
('le-chamber',        '르챔버',       'Le Chamber',       '서울 강남구 도산대로55길 42',    37.5251200, 127.0442300, '02-542-1002', '책장 뒤에 숨은 입구로 유명한 클래식 칵테일 바.',       '/uploads/bars/le-chamber.webp',        '{"mon":"19:00-03:00","tue":"19:00-03:00","wed":"19:00-03:00","thu":"19:00-03:00","fri":"19:00-04:00","sat":"19:00-04:00","sun":"19:00-01:00"}'::jsonb, 'ACTIVE', 9.0),
('charles-h',         '찰스 에이치',   'Charles H.',       '서울 중구 동호로 249',           37.5601400, 126.9812200, '02-317-1003', '지하에 자리한 호텔 바. 시그니처 하이볼로 알려져 있다.', '/uploads/bars/charles-h.webp',         '{"mon":"18:00-01:00","tue":"18:00-01:00","wed":"18:00-01:00","thu":"18:00-01:00","fri":"18:00-02:00","sat":"18:00-02:00","sun":"18:00-00:00"}'::jsonb, 'ACTIVE', 8.5),
('zest-gangnam',      '제스트',       'Zest',             '서울 강남구 도산대로17길 39',    37.5227800, 127.0355600, '02-546-1004', '지속가능성을 주제로 한 시그니처 칵테일 바.',           '/uploads/bars/zest-gangnam.webp',      '{"mon":"closed","tue":"18:00-01:00","wed":"18:00-01:00","thu":"18:00-01:00","fri":"18:00-02:00","sat":"18:00-02:00","sun":"18:00-00:00"}'::jsonb, 'ACTIVE', 8.8),
('bar-cham',          '바 참',        'Bar Cham',         '서울 종로구 삼일대로32길 12',    37.5741300, 126.9877700, '02-720-1005', '한국 재료를 사용한 칵테일로 알려진 북촌의 바.',        '/uploads/bars/bar-cham.webp',          '{"mon":"18:00-01:00","tue":"18:00-01:00","wed":"18:00-01:00","thu":"18:00-01:00","fri":"18:00-02:00","sat":"18:00-02:00","sun":"closed"}'::jsonb, 'ACTIVE', 8.2),
('sunset-seongsu',    '선셋 성수',    'Sunset Seongsu',   '서울 성동구 연무장길 25',        37.5445300, 127.0557800, '02-462-1006', '성수동 골목의 루프탑 칵테일 바.',                     '/uploads/bars/sunset-seongsu.webp',    '{"mon":"18:00-01:00","tue":"18:00-01:00","wed":"18:00-01:00","thu":"18:00-01:00","fri":"18:00-03:00","sat":"18:00-03:00","sun":"18:00-00:00"}'::jsonb, 'ACTIVE', 7.9),
('mixology-euljiro',  '믹솔로지 을지로','Mixology Euljiro', '서울 중구 을지로12길 14',        37.5663800, 126.9915400, '02-2273-1007', '을지로 인쇄골목 3층의 좁고 조용한 바.',              '/uploads/bars/mixology-euljiro.webp',  '{"mon":"19:00-02:00","tue":"19:00-02:00","wed":"19:00-02:00","thu":"19:00-02:00","fri":"19:00-03:00","sat":"19:00-03:00","sun":"closed"}'::jsonb, 'ACTIVE', 7.4),
('smoke-itaewon',     '스모크 이태원', 'Smoke Itaewon',    '서울 용산구 이태원로27가길 36',  37.5343200, 126.9944100, '02-794-1008', '스모키한 위스키 베이스 칵테일 전문.',                  '/uploads/bars/smoke-itaewon.webp',     '{"mon":"20:00-03:00","tue":"20:00-03:00","wed":"20:00-03:00","thu":"20:00-03:00","fri":"20:00-04:00","sat":"20:00-04:00","sun":"20:00-01:00"}'::jsonb, 'ACTIVE', 7.1),
('velvet-hongdae',    '벨벳 홍대',    'Velvet Hongdae',   '서울 마포구 와우산로29길 8',     37.5548900, 126.9236700, '02-333-1009', '홍대 뒷골목의 캐주얼한 칵테일 바.',                    '/uploads/bars/velvet-hongdae.webp',    '{"mon":"19:00-02:00","tue":"19:00-02:00","wed":"19:00-02:00","thu":"19:00-02:00","fri":"19:00-04:00","sat":"19:00-04:00","sun":"19:00-01:00"}'::jsonb, 'ACTIVE', 6.8),
('nocturne-yeonnam',  '녹턴 연남',    'Nocturne Yeonnam', '서울 마포구 성미산로 161',       37.5629400, 126.9250300, '02-322-1010', '연남동 주택가의 야간 전용 라운지 바.',                 '/uploads/bars/nocturne-yeonnam.webp',  '{"mon":"closed","tue":"19:00-01:00","wed":"19:00-01:00","thu":"19:00-01:00","fri":"19:00-03:00","sat":"19:00-03:00","sun":"19:00-00:00"}'::jsonb, 'ACTIVE', 6.5),
('anchor-yeouido',    '앵커 여의도',  'Anchor Yeouido',   '서울 영등포구 여의대로 108',     37.5254100, 126.9273900, '02-761-1011', '여의도 오피스 상권의 애프터워크 바.',                  '/uploads/bars/anchor-yeouido.webp',    '{"mon":"17:00-00:00","tue":"17:00-00:00","wed":"17:00-00:00","thu":"17:00-01:00","fri":"17:00-02:00","sat":"closed","sun":"closed"}'::jsonb, 'ACTIVE', 6.0),
('lantern-jongno',    '랜턴 종로',    'Lantern Jongno',   '서울 종로구 종로 51',            37.5702500, 126.9880600, '02-733-1012', '종로 뒷골목 2층의 작은 클래식 바.',                    '/uploads/bars/lantern-jongno.webp',    '{"mon":"18:00-01:00","tue":"18:00-01:00","wed":"18:00-01:00","thu":"18:00-01:00","fri":"18:00-02:00","sat":"18:00-02:00","sun":"closed"}'::jsonb, 'ACTIVE', 5.6);

-- ── 메뉴: 바마다 카테고리 3개 × 아이템 5개 ─────────────────────────────
-- 카테고리: 시그니처 / 클래식 / 논알콜
INSERT INTO bar_menu_category (bar_id, name_ko, name_en, priority)
SELECT b.id, c.name_ko, c.name_en, c.priority
  FROM bar b
 CROSS JOIN (VALUES
        ('시그니처', 'Signature', 0.0),
        ('클래식',   'Classic',   1.0),
        ('논알콜',   'Non-Alcoholic', 2.0)
 ) AS c(name_ko, name_en, priority);

-- 시그니처 5종 (바별 가격 편차: featured_weight 가 높을수록 비싸게)
INSERT INTO bar_menu_item (bar_id, category_id, name, name_en, price, price_amount, description, priority)
SELECT cat.bar_id, cat.id, i.name, i.name_en,
       to_char(i.base + (b.featured_weight * 400)::int, 'FM999,999') || '원',
       i.base + (b.featured_weight * 400)::int,
       i.description, i.priority
  FROM bar_menu_category cat
  JOIN bar b ON b.id = cat.bar_id
 CROSS JOIN (VALUES
        ('하우스 시그니처', 'House Signature', 18000, '이 바의 대표 칵테일.',            0.0),
        ('스모크 올드패션', 'Smoked Old Fashioned', 21000, '훈연 향을 입힌 올드패션.',  1.0),
        ('시트러스 하이볼', 'Citrus Highball', 15000, '상큼한 시트러스 하이볼.',        2.0),
        ('바텐더 초이스',   'Bartender''s Choice', 22000, '취향을 말하면 만들어 드립니다.', 3.0),
        ('제철 스매시',     'Seasonal Smash', 17000, '제철 과일로 만드는 스매시.',       4.0)
 ) AS i(name, name_en, base, description, priority)
 WHERE cat.name_ko = '시그니처';

-- 클래식 5종: 레시피북(cocktail) 과 연결 → BarDetail.signatureCocktails 산출원
INSERT INTO bar_menu_item (bar_id, category_id, name, name_en, price, price_amount, description, priority, cocktail_id)
SELECT cat.bar_id, cat.id, c.kor_name, c.eng_name,
       to_char(14000 + (row_number() OVER (PARTITION BY cat.bar_id ORDER BY c.id))::int * 1500, 'FM999,999') || '원',
       14000 + (row_number() OVER (PARTITION BY cat.bar_id ORDER BY c.id))::int * 1500,
       '클래식 레시피 그대로.',
       (row_number() OVER (PARTITION BY cat.bar_id ORDER BY c.id))::double precision,
       c.id
  FROM bar_menu_category cat
  JOIN LATERAL (
        SELECT id, kor_name, eng_name FROM cocktail ORDER BY id LIMIT 5
  ) c ON true
 WHERE cat.name_ko = '클래식';

-- 논알콜 5종 (하나는 "시가" → price_amount NULL → priceBand HIGH 경로 검증용)
INSERT INTO bar_menu_item (bar_id, category_id, name, name_en, price, price_amount, description, priority)
SELECT cat.bar_id, cat.id, i.name, i.name_en, i.price, i.amount, i.description, i.priority
  FROM bar_menu_category cat
 CROSS JOIN (VALUES
        ('버진 모히토',   'Virgin Mojito',   '9,000원',  9000,  '럼을 뺀 모히토.',        0.0),
        ('시트러스 소다', 'Citrus Soda',     '8,000원',  8000,  '자몽과 라임 소다.',      1.0),
        ('진저 쿨러',     'Ginger Cooler',   '9,500원',  9500,  '수제 진저 시럽.',        2.0),
        ('콜드브루 토닉', 'Cold Brew Tonic', '10,000원', 10000, '콜드브루와 토닉.',       3.0),
        ('오늘의 무알콜', 'Today''s Zero',   '시가',     NULL,  '재료에 따라 매일 달라집니다.', 4.0)
 ) AS i(name, name_en, price, amount, description, priority)
 WHERE cat.name_ko = '논알콜';
