-- ═══════════════════════════════════════════════════════════════════════
-- V6__bar_trust_and_chat.sql  —  QR/방문세션(T-11) + 익명채팅(T-13) + 모더레이션(T-14)
--
-- 설계 원칙 (plan_FINAL §5, §6):
--   1. QR = 의도, GPS = 증명.
--      인쇄된 플래카드는 회전할 수 없으므로 QR 자체는 **장기 서명**이다.
--      "지금 매장 안에 있다"는 사실은 오직 GPS 가 증명한다.
--   2. 신뢰등급
--      L0 = 반경 밖/무효 → 거부
--      L1 = GPS 반경 내 (QR 없음)        → 채팅만.  ★ 구버전 앱 하위호환 ★
--      L2 = GPS 반경 내 + 유효 QR + !mock → 채팅 + 가격
--   3. **익명성은 스키마에서 온다.** bar_chat_message 에 member_id 컬럼이 없다.
--      역추적은 분리 테이블 bar_chat_identity 를 통해서만 가능하고, 30일 후 파기된다.
--
-- 컬럼 snake_case / 응답 JSON camelCase. ddl-auto:validate 와 1:1 정합.
-- ═══════════════════════════════════════════════════════════════════════

-- ── QR 플래카드 ────────────────────────────────────────────────────────
-- 매장 벽에 인쇄되어 붙는 물리 QR 1종 = 1행. key_version 을 올려 폐기(회전)한다.
CREATE TABLE bar_qr_placard (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id      BIGINT       NOT NULL REFERENCES bar(id) ON DELETE CASCADE,
    key_version INTEGER      NOT NULL,
    secret      VARCHAR(120) NOT NULL,          -- HMAC 키. 플래카드마다 독립
    label       VARCHAR(60),                    -- '입구', '4번 테이블'
    issued_at   TIMESTAMP(6) NOT NULL DEFAULT now(),
    revoked_at  TIMESTAMP(6),                   -- NOT NULL 이면 폐기됨
    scan_count  INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_qr_placard UNIQUE (bar_id, key_version)
);
CREATE INDEX bar_qr_placard_bar_idx ON bar_qr_placard(bar_id) WHERE revoked_at IS NULL;

-- ── 방문 세션 ──────────────────────────────────────────────────────────
-- token 은 평문 저장하지 않는다(sha256 만). 유출되어도 DB 에서 재사용 불가.
CREATE TABLE bar_visit_session (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id         BIGINT        NOT NULL REFERENCES bar(id)    ON DELETE CASCADE,
    member_id      BIGINT        NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    token_hash     VARCHAR(64)   NOT NULL UNIQUE,
    trust_level    VARCHAR(2)    NOT NULL CHECK (trust_level IN ('L1','L2')),
    issued_at      TIMESTAMP(6)  NOT NULL DEFAULT now(),
    expires_at     TIMESTAMP(6)  NOT NULL,
    last_lat       NUMERIC(10,7) NOT NULL,
    last_lng       NUMERIC(10,7) NOT NULL,
    last_proof_at  TIMESTAMP(6)  NOT NULL DEFAULT now(),
    renew_count    INTEGER       NOT NULL DEFAULT 0,
    mock_suspected BOOLEAN       NOT NULL DEFAULT false,
    revoked        BOOLEAN       NOT NULL DEFAULT false,
    revoke_reason  VARCHAR(40)
);
CREATE INDEX bar_visit_session_lookup_idx ON bar_visit_session(token_hash) WHERE revoked = false;
CREATE INDEX bar_visit_session_member_idx ON bar_visit_session(member_id, issued_at DESC);

-- ── 채팅 익명 신원 (역추적 창구. 30일 후 파기) ──────────────────────────
CREATE TABLE bar_chat_identity (
    author_ref  VARCHAR(32)  PRIMARY KEY,       -- HMAC(memberId|barId|epochDate)[:32]
    member_id   BIGINT       NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    bar_id      BIGINT       NOT NULL REFERENCES bar(id)    ON DELETE CASCADE,
    epoch_date  DATE         NOT NULL,
    nickname    VARCHAR(60)  NOT NULL,
    muted_until TIMESTAMP(6),
    created_at  TIMESTAMP(6) NOT NULL DEFAULT now(),
    CONSTRAINT uk_chat_identity UNIQUE (member_id, bar_id, epoch_date)
);
CREATE INDEX bar_chat_identity_purge_idx ON bar_chat_identity(created_at);

-- ── 채팅 메시지 ────────────────────────────────────────────────────────
-- ⚠️ member_id 컬럼이 없다. 이것이 익명성의 근거다. 되살리지 말 것.
CREATE TABLE bar_chat_message (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id        BIGINT       NOT NULL REFERENCES bar(id) ON DELETE CASCADE,
    author_ref    VARCHAR(32)  NOT NULL,
    content       VARCHAR(500) NOT NULL,
    status        VARCHAR(10)  NOT NULL DEFAULT 'VISIBLE'
                  CHECK (status IN ('VISIBLE','HIDDEN','DELETED')),
    hidden_reason VARCHAR(40),
    report_count  INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT now()
);
CREATE INDEX bar_chat_message_stream_idx ON bar_chat_message(bar_id, id DESC);
CREATE INDEX bar_chat_message_purge_idx  ON bar_chat_message(created_at);

-- ── 신고 ───────────────────────────────────────────────────────────────
CREATE TABLE bar_chat_report (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id   BIGINT       NOT NULL REFERENCES bar_chat_message(id) ON DELETE CASCADE,
    reporter_ref VARCHAR(32)  NOT NULL,
    reason       VARCHAR(16)  NOT NULL
                 CHECK (reason IN ('SPAM','ABUSE','SEXUAL','ADVERTISE','OTHER')),
    detail       VARCHAR(300),
    created_at   TIMESTAMP(6) NOT NULL DEFAULT now(),
    -- 같은 사람이 같은 메시지를 여러 번 신고해 임계치를 혼자 채우는 것을 막는다
    CONSTRAINT uk_chat_report_once UNIQUE (message_id, reporter_ref)
);

-- ── 차단 ───────────────────────────────────────────────────────────────
CREATE TABLE bar_chat_block (
    blocker_ref VARCHAR(32)  NOT NULL,
    blocked_ref VARCHAR(32)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT now(),
    PRIMARY KEY (blocker_ref, blocked_ref)
);

-- ── 시드: 바 12곳에 QR 플래카드 1장씩 (key_version = 1) ─────────────────
-- 로컬 검증용 결정적 시크릿. 프로덕션은 관리자 페이지(T-19)가 랜덤 생성한다.
INSERT INTO bar_qr_placard (bar_id, key_version, secret, label)
SELECT b.id, 1, 'seed-secret-' || b.slug, '입구' FROM bar b;
